import { z } from "zod";


// Define a tuple type that matches the expected type
type Tuple = [string, ...string[]];


// Your array of states
const states: readonly string[] = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California",
  "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
  "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
  "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
  "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
  "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
  "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma",
  "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
  "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
  "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
];

const roles: readonly string[] = ["USER", "ADMIN"];

const eventTypes: readonly string[] = [
  "Birthday", "Wedding",
];

export const countries = [
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Albania", value: "albania" },
  { label: "Algeria", value: "algeria" },
  { label: "Andorra", value: "andorra" },
  { label: "Angola", value: "angola" },
  { label: "Antigua and Barbuda", value: "antiguaandbarbuda" },
  { label: "Argentina", value: "argentina" },
  { label: "Armenia", value: "armenia" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas", value: "bahamas" },
  { label: "Bahrain", value: "bahrain" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  { label: "Belarus", value: "belarus" },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  { label: "Benin", value: "benin" },
  { label: "Bhutan", value: "bhutan" },
  { label: "Bolivia", value: "bolivia" },
  { label: "Bosnia and Herzegovina", value: "bosniaandherzegovina" },
  { label: "Botswana", value: "botswana" },
  { label: "Brazil", value: "brazil" },
  { label: "Brunei", value: "brunei" },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkinafaso" },
  { label: "Burundi", value: "burundi" },
  { label: "Cabo Verde", value: "caboverde" },
  { label: "Cambodia", value: "cambodia" },
  { label: "Cameroon", value: "cameroon" },
  { label: "Canada", value: "canada" },
  { label: "Central African Republic", value: "centralafricanrepublic" },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  { label: "China", value: "china" },
  { label: "Colombia", value: "colombia" },
  { label: "Comoros", value: "comoros" },
  { label: "Congo (Congo-Brazzaville)", value: "congo(congo-brazzaville)" },
  { label: "Costa Rica", value: "costarica" },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  { label: "Cyprus", value: "cyprus" },
  { label: "Czechia (Czech Republic)", value: "czechia(czechrepublic)" },
  { label: "Democratic Republic of the Congo", value: "democraticrepublicofthecongo" },
  { label: "Denmark", value: "denmark" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominica", value: "dominica" },
  { label: "Dominican Republic", value: "dominicanrepublic" },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  { label: "El Salvador", value: "elsalvador" },
  { label: "Equatorial Guinea", value: "equatorialguinea" },
  { label: "Eritrea", value: "eritrea" },
  { label: "Estonia", value: "estonia" },
  { label: "Eswatini (fmr. Swaziland)", value: "eswatini(fmr.swaziland)" },
  { label: "Ethiopia", value: "ethiopia" },
  { label: "Fiji", value: "fiji" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "Gabon", value: "gabon" },
  { label: "Gambia", value: "gambia" },
  { label: "Georgia", value: "georgia" },
  { label: "Germany", value: "germany" },
  { label: "Ghana", value: "ghana" },
  { label: "Greece", value: "greece" },
  { label: "Grenada", value: "grenada" },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guinea", value: "guinea" },
  { label: "Guinea-Bissau", value: "guinea-bissau" },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  { label: "Honduras", value: "honduras" },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran", value: "iran" },
  { label: "Iraq", value: "iraq" },
  { label: "Ireland", value: "ireland" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  { label: "Jordan", value: "jordan" },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  { label: "Kiribati", value: "kiribati" },
  { label: "Korea, North", value: "korea,north" },
  { label: "Korea, South", value: "korea,south" },
  { label: "Kosovo", value: "kosovo" },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  { label: "Laos", value: "laos" },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  { label: "Lesotho", value: "lesotho" },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  { label: "Madagascar", value: "madagascar" },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Maldives", value: "maldives" },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  { label: "Marshall Islands", value: "marshallislands" },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  { label: "Mexico", value: "mexico" },
  { label: "Micronesia", value: "micronesia" },
  { label: "Moldova", value: "moldova" },
  { label: "Monaco", value: "monaco" },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  { label: "Morocco", value: "morocco" },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar (formerly Burma)", value: "myanmar(formerlyburma)" },
  { label: "Namibia", value: "namibia" },
  { label: "Nauru", value: "nauru" },
  { label: "Nepal", value: "nepal" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Zealand", value: "newzealand" },
  { label: "Nicaragua", value: "nicaragua" },
  { label: "Niger", value: "niger" },
  { label: "Nigeria", value: "nigeria" },
  { label: "North Macedonia", value: "northmacedonia" },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Palau", value: "palau" },
  { label: "Palestine State", value: "palestinestate" },
  { label: "Panama", value: "panama" },
  { label: "Papua New Guinea", value: "papuanewguinea" },
  { label: "Paraguay", value: "paraguay" },
  { label: "Peru", value: "peru" },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Qatar", value: "qatar" },
  { label: "Romania", value: "romania" },
  { label: "Russia", value: "russia" },
  { label: "Rwanda", value: "rwanda" },
  { label: "Saint Kitts and Nevis", value: "saintkittsandnevis" },
  { label: "Saint Lucia", value: "saintlucia" },
  { label: "Saint Vincent and the Grenadines", value: "saintvincentandthegrenadines" },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "sanmarino" },
  { label: "Sao Tome and Principe", value: "saotomeandprincipe" },
  { label: "Saudi Arabia", value: "saudiarabia" },
  { label: "Senegal", value: "senegal" },
  { label: "Serbia", value: "serbia" },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierraleone" },
  { label: "Singapore", value: "singapore" },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  { label: "Solomon Islands", value: "solomonislands" },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "southafrica" },
  { label: "South Sudan", value: "southsudan" },
  { label: "Spain", value: "spain" },
  { label: "Sri Lanka", value: "srilanka" },
  { label: "Sudan", value: "sudan" },
  { label: "Suriname", value: "suriname" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syria", value: "syria" },
  { label: "Tajikistan", value: "tajikistan" },
  { label: "Tanzania", value: "tanzania" },
  { label: "Thailand", value: "thailand" },
  { label: "Timor-Leste", value: "timor-leste" },
  { label: "Togo", value: "togo" },
  { label: "Tonga", value: "tonga" },
  { label: "Trinidad and Tobago", value: "trinidadandtobago" },
  { label: "Tunisia", value: "tunisia" },
  { label: "Turkey", value: "turkey" },
  { label: "Turkmenistan", value: "turkmenistan" },
  { label: "Tuvalu", value: "tuvalu" },
  { label: "Uganda", value: "uganda" },
  { label: "Ukraine", value: "ukraine" },
  { label: "United Arab Emirates", value: "unitedarabemirates" },
  { label: "United Kingdom", value: "unitedkingdom" },
  { label: "United States", value: "unitedstates" },
  { label: "Uruguay", value: "uruguay" },
  { label: "Uzbekistan", value: "uzbekistan" },
  { label: "Vanuatu", value: "vanuatu" },
  { label: "Vatican City", value: "vaticancity" },
  { label: "Venezuela", value: "venezuela" },
  { label: "Vietnam", value: "vietnam" },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
] as const;

export const areaCodes = [
  { label: "Afghanistan", value: "+93AF" },
  { label: "Albania", value: "+355AL" },
  { label: "Algeria", value: "+213DZ" },
  { label: "American Samoa", value: "+1AS" },
  { label: "Andorra", value: "+376AD" },
  { label: "Angola", value: "+244AO" },
  { label: "Anguilla", value: "+1AI" },
  { label: "Antigua and Barbuda", value: "+1AG" },
  { label: "Argentina", value: "+54AR" },
  { label: "Armenia", value: "+374AM" },
  { label: "Aruba", value: "+297AW" },
  { label: "Australia", value: "+61AU" },
  { label: "Austria", value: "+43AT" },
  { label: "Azerbaijan", value: "+994AZ" },
  { label: "Bahamas", value: "+1BS" },
  { label: "Bahrain", value: "+973BH" },
  { label: "Bangladesh", value: "+880BD" },
  { label: "Barbados", value: "+1BB" },
  { label: "Belarus", value: "+375BY" },
  { label: "Belgium", value: "+32BE" },
  { label: "Belize", value: "+501BZ" },
  { label: "Benin", value: "+229BJ" },
  { label: "Bermuda", value: "+1BM" },
  { label: "Bhutan", value: "+975BT" },
  { label: "Bolivia", value: "+591BO" },
  { label: "Bosnia and Herzegovina", value: "+387BA" },
  { label: "Botswana", value: "+267BW" },
  { label: "Brazil", value: "+55BR" },
  { label: "Brunei", value: "+673BN" },
  { label: "Bulgaria", value: "+359BG" },
  { label: "Burkina Faso", value: "+226BF" },
  { label: "Burundi", value: "+257BI" },
  { label: "Cabo Verde", value: "+238CV" },
  { label: "Cambodia", value: "+855KH" },
  { label: "Cameroon", value: "+237CM" },
  { label: "Canada", value: "+1CA" },
  { label: "Cayman Islands", value: "+1KY" },
  { label: "Central African Republic", value: "+236CF" },
  { label: "Chad", value: "+235TD" },
  { label: "Chile", value: "+56CL" },
  { label: "China", value: "+86CN" },
  { label: "Colombia", value: "+57CO" },
  { label: "Comoros", value: "+269KM" },
  { label: "Congo", value: "+242CG" },
  { label: "Cook Islands", value: "+682CK" },
  { label: "Costa Rica", value: "+506CR" },
  { label: "Croatia", value: "+385HR" },
  { label: "Cuba", value: "+53CU" },
  { label: "Curaçao", value: "+599CW" },
  { label: "Cyprus", value: "+357CY" },
  { label: "Czech Republic", value: "+420CZ" },
  { label: "Denmark", value: "+45DK" },
  { label: "Djibouti", value: "+253DJ" },
  { label: "Dominica", value: "+1DM" },
  { label: "Dominican Republic", value: "+1DO" },
  { label: "Ecuador", value: "+593EC" },
  { label: "Egypt", value: "+20EG" },
  { label: "El Salvador", value: "+503SV" },
  { label: "Equatorial Guinea", value: "+240GQ" },
  { label: "Eritrea", value: "+291ER" },
  { label: "Estonia", value: "+372EE" },
  { label: "Eswatini", value: "+268SZ" },
  { label: "Ethiopia", value: "+251ET" },
  { label: "Falkland Islands", value: "+500FK" },
  { label: "Faroe Islands", value: "+298FO" },
  { label: "Fiji", value: "+679FJ" },
  { label: "Finland", value: "+358FI" },
  { label: "France", value: "+33FR" },
  { label: "French Guiana", value: "+594GF" },
  { label: "French Polynesia", value: "+689PF" },
  { label: "Gabon", value: "+241GA" },
  { label: "Gambia", value: "+220GM" },
  { label: "Georgia", value: "+995GE" },
  { label: "Germany", value: "+49DE" },
  { label: "Ghana", value: "+233GH" },
  { label: "Gibraltar", value: "+350GI" },
  { label: "Greece", value: "+30GR" },
  { label: "Greenland", value: "+299GL" },
  { label: "Grenada", value: "+1GD" },
  { label: "Guadeloupe", value: "+590GP" },
  { label: "Guam", value: "+1GU" },
  { label: "Guatemala", value: "+502GT" },
  { label: "Guernsey", value: "+44GG" },
  { label: "Guinea", value: "+224GN" },
  { label: "Guinea-Bissau", value: "+245GW" },
  { label: "Guyana", value: "+592GY" },
  { label: "Haiti", value: "+509HT" },
  { label: "Honduras", value: "+504HN" },
  { label: "Hong Kong", value: "+852HK" },
  { label: "Hungary", value: "+36HU" },
  { label: "Iceland", value: "+354IS" },
  { label: "India", value: "+91IN" },
  { label: "Indonesia", value: "+62ID" },
  { label: "Iran", value: "+98IR" },
  { label: "Iraq", value: "+964IQ" },
  { label: "Ireland", value: "+353IE" },
  { label: "Isle of Man", value: "+44IM" },
  { label: "Israel", value: "+972IL" },
  { label: "Italy", value: "+39IT" },
  { label: "Jamaica", value: "+1JM" },
  { label: "Japan", value: "+81JP" },
  { label: "Jersey", value: "+44JE" },
  { label: "Jordan", value: "+962JO" },
  { label: "Kazakhstan", value: "+7KZ" },
  { label: "Kenya", value: "+254KE" },
  { label: "Kiribati", value: "+686KI" },
  { label: "Kuwait", value: "+965KW" },
  { label: "Kyrgyzstan", value: "+996KG" },
  { label: "Laos", value: "+856LA" },
  { label: "Latvia", value: "+371LV" },
  { label: "Lebanon", value: "+961LB" },
  { label: "Lesotho", value: "+266LS" },
  { label: "Liberia", value: "+231LR" },
  { label: "Libya", value: "+218LY" },
  { label: "Liechtenstein", value: "+423LI" },
  { label: "Lithuania", value: "+370LT" },
  { label: "Luxembourg", value: "+352LU" },
  { label: "Macau", value: "+853MO" },
  { label: "Madagascar", value: "+261MG" },
  { label: "Malawi", value: "+265MW" },
  { label: "Malaysia", value: "+60MY" },
  { label: "Maldives", value: "+960MV" },
  { label: "Mali", value: "+223ML" },
  { label: "Malta", value: "+356MT" },
  { label: "Marshall Islands", value: "+692MH" },
  { label: "Martinique", value: "+596MQ" },
  { label: "Mauritania", value: "+222MR" },
  { label: "Mauritius", value: "+230MU" },
  { label: "Mayotte", value: "+262YT" },
  { label: "Mexico", value: "+52MX" },
  { label: "Micronesia", value: "+691FM" },
  { label: "Moldova", value: "+373MD" },
  { label: "Monaco", value: "+377MC" },
  { label: "Mongolia", value: "+976MN" },
  { label: "Montenegro", value: "+382ME" },
  { label: "Montserrat", value: "+1MS" },
  { label: "Morocco", value: "+212MA" },
  { label: "Mozambique", value: "+258MZ" },
  { label: "Myanmar", value: "+95MM" },
  { label: "Namibia", value: "+264NA" },
  { label: "Nauru", value: "+674NR" },
  { label: "Nepal", value: "+977NP" },
  { label: "Netherlands", value: "+31NL" },
  { label: "New Caledonia", value: "+687NC" },
  { label: "New Zealand", value: "+64NZ" },
  { label: "Nicaragua", value: "+505NI" },
  { label: "Niger", value: "+227NE" },
  { label: "Nigeria", value: "+234NG" },
  { label: "Niue", value: "+683NU" },
  { label: "Norfolk Island", value: "+672NF" },
  { label: "North Korea", value: "+850KP" },
  { label: "North Macedonia", value: "+389MK" },
  { label: "Northern Mariana Islands", value: "+1MP" },
  { label: "Norway", value: "+47NO" },
  { label: "Oman", value: "+968OM" },
  { label: "Pakistan", value: "+92PK" },
  { label: "Palau", value: "+680PW" },
  { label: "Palestine", value: "+970PS" },
  { label: "Panama", value: "+507PA" },
  { label: "Papua New Guinea", value: "+675PG" },
  { label: "Paraguay", value: "+595PY" },
  { label: "Peru", value: "+51PE" },
  { label: "Philippines", value: "+63PH" },
  { label: "Pitcairn Islands", value: "+64PN" },
  { label: "Poland", value: "+48PL" },
  { label: "Portugal", value: "+351PT" },
  { label: "Puerto Rico", value: "+1PR" },
  { label: "Qatar", value: "+974QA" },
  { label: "Réunion", value: "+262RE" },
  { label: "Romania", value: "+40RO" },
  { label: "Russia", value: "+7RU" },
  { label: "Rwanda", value: "+250RW" },
  { label: "Saint Barthélemy", value: "+590BL" },
  { label: "Saint Helena", value: "+290SH" },
  { label: "Saint Kitts and Nevis", value: "+1KN" },
  { label: "Saint Lucia", value: "+1LC" },
  { label: "Saint Martin", value: "+590MF" },
  { label: "Saint Pierre and Miquelon", value: "+508PM" },
  { label: "Saint Vincent and the Grenadines", value: "+1VC" },
  { label: "Samoa", value: "+685WS" },
  { label: "San Marino", value: "+378SM" },
  { label: "São Tomé and Príncipe", value: "+239ST" },
  { label: "Saudi Arabia", value: "+966SA" },
  { label: "Senegal", value: "+221SN" },
  { label: "Serbia", value: "+381RS" },
  { label: "Seychelles", value: "+248SC" },
  { label: "Sierra Leone", value: "+232SL" },
  { label: "Singapore", value: "+65SG" },
  { label: "Sint Maarten", value: "+1SX" },
  { label: "Slovakia", value: "+421SK" },
  { label: "Slovenia", value: "+386SI" },
  { label: "Solomon Islands", value: "+677SB" },
  { label: "Somalia", value: "+252SO" },
  { label: "South Africa", value: "+27ZA" },
  { label: "South Korea", value: "+82KR" },
  { label: "South Sudan", value: "+211SS" },
  { label: "Spain", value: "+34ES" },
  { label: "Sri Lanka", value: "+94LK" },
  { label: "Sudan", value: "+249SD" },
  { label: "Suriname", value: "+597SR" },
  { label: "Sweden", value: "+46SE" },
  { label: "Switzerland", value: "+41CH" },
  { label: "Syria", value: "+963SY" },
  { label: "Taiwan", value: "+886TW" },
  { label: "Tajikistan", value: "+992TJ" },
  { label: "Tanzania", value: "+255TZ" },
  { label: "Thailand", value: "+66TH" },
  { label: "Timor-Leste", value: "+670TL" },
  { label: "Togo", value: "+228TG" },
  { label: "Tokelau", value: "+690TK" },
  { label: "Tonga", value: "+676TO" },
  { label: "Trinidad and Tobago", value: "+1TT" },
  { label: "Tunisia", value: "+216TN" },
  { label: "Turkey", value: "+90TR" },
  { label: "Turkmenistan", value: "+993TM" },
  { label: "Turks and Caicos Islands", value: "+1TC" },
  { label: "Tuvalu", value: "+688TV" },
  { label: "Uganda", value: "+256UG" },
  { label: "Ukraine", value: "+380UA" },
  { label: "United Arab Emirates", value: "+971AE" },
  { label: "United Kingdom", value: "+44GB" },
  { label: "United States", value: "+1US" },
  { label: "Uruguay", value: "+598UY" },
  { label: "Uzbekistan", value: "+998UZ" },
  { label: "Vanuatu", value: "+678VU" },
  { label: "Vatican City", value: "+39VA" },
  { label: "Venezuela", value: "+58VE" },
  { label: "Vietnam", value: "+84VN" },
  { label: "Wallis and Futuna", value: "+681WF" },
  { label: "Yemen", value: "+967YE" },
  { label: "Zambia", value: "+260ZM" },
  { label: "Zimbabwe", value: "+263ZW" },
] as const;


// Convert the readonly string[] to the expected tuple type
export const statesTuple: Tuple = states as Tuple;
export const rolesTuple: Tuple = roles as Tuple;
export const eventTypesTuple: Tuple = eventTypes as Tuple;

export const EventTypesEnum = z.enum(eventTypes as [string]);
