version: "3.7"

services:
    database:
        image: postgres:alpine
        container_name: ${APP_NAME}-database-${APP_ENV}
        env_file:
            - ./.env
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - evdata:/var/lib/postgresql/data
        restart: always

volumes:
    evdata:
